level-seed=960002
level-name=world-960002
motd=\u00A76X\u00A7r Minecraft Server
difficulty=normal
online-mode=false
enforce-secure-profile=false
server-port=25565
max-players=5
pause-when-empty-seconds=60
view-distance=24
spawn-protection=0
